This is a case for silica gel that is inside the filament case. 

It is powered to monitor the humidity level and to run a fan forcing the humid air over the silica gel which greatly improves the reduction in humidity.

All measurements are in mm and from outside edges.

Case designed with http://www.makercase.com/


Files:
* GelCase-V2.02.svg - master svg as generated by MakerCase. Do not use for cutting
* GelCase-V2.02.json - master MakerCase model.
* Sheet-1-V2.02 - Cutting.svg - svg used to generate dxf for cutting. Has better layout. Cut from 600mm x 400mm x 5mm acrylic.
* FanInsert-V2.02.svg - the fan insert to fit cutouts defined in the gel case. This holds a 40mm fan. Fan needs filter to prevent inflow of silica gel.

Use only these for cutting the acrylic.
* Sheet-1-V2.02 - Cutting.svg
* FanInsert-V2.02.svg

Notes:
* In MakerCase the top and bottom are transposed. This readme refers to "Bottom" and "Top" as they are references in MakerCase with (actually ...) added to point out the final 
* When loading the json file into MakerCase ("Load Model" button) the material thickness is not correctly reloaded - use "Custom Material Thickness" and set to 5mm.


Assembly:
*Case should be glued on all sides except 
** The bottom (actually top) - the 2 part long piece with round power hole and 6 mounting holes.
** The fan insert
* Tensol 12 should be used for gluing the acrylic.
* Refrigerate glue for 12 hours before use.
* Remove protective cover fom acrylic for all except the bottom (aka top).
* Use electrical tape to hold the pieces together when gluing.
* Allow 3-4 hours for the glue to set (watch for glue leaking through joint - clean up as needed - don't rest on paper towels as it sticks)
* You may wish to fit the bottom (aka top) whilst the glue sets to help keep the case square but be careful it isn't glued inadvertantly via the glue up the sides


Dimensions
-----------

Outside:
--------
Height: 60 
Width: 100
Length: 300


Top (actually bottom):
------

Vent holes.

x 10 to 90 every 10mm
y 90 to 290 every 10mm

Large air intake:
* 15,20 -> 85,70 (70x50 mm) (buts up to fan mount

Top/Bottom connector mounts

M4 holes. 8mm support for 3mm screw.
8/2 = 4mm offset for center.
12 mm from each corner.

* M4 10,10
* M4 90,10
- first section
* M4 10,240
* M4 90,240

* M4 10,290
* M4 90,290



Bottom (actually top):
-------
Do not glue to rest of cased. It is removable to allow PCB to be accessed and gel to be replaced.

Helpd in place by screws to fan assembly and side moning screws.

Holes to align with top holes for fan/PCB enclosure.


- first secotion
* M4 10,290
* M4 90,290
* M4 10,60
* M4 90,60
- second section
* M4 10,10
* M4 90,10


M4 - Fan case (Not used)
* 19,345 - 20
* 81,345 - 20
* 19,345 - 102,
* 81,345 - 102

{"params":[19,20,4,5],"type":"roundHole"},
{"params":[81,20,4,6],"type":"roundHole"},
{"params":[81,102,4,7],"type":"roundHole"},
{"params":[19,102,4,8],"type":"roundHole"},

Back:
-------
PCB mount:
* M4 @ 24,11
* M4 @ 24,49
* M4 @ 76,11
* M4 @ 76,49


Extra:
-------

Cut line at 245mm in bottom to allow small segment to be removed for easier emptying.

** Holes in tabs to allow for fixing of top and lower segment.


Internal partition
-------------------

M4 - Fan mount.
x,y,size, index
* {"params":[66,29,4,1],"type":"roundHole"},
* {"params":[34,29,4,2],"type":"roundHole"},
* {"params":[66,61,4,3],"type":"roundHole"},
* {"params":[34,61,4,4],"type":"roundHole"},

M4 - Fan case
* 19, 20
* 81,20
* 19,102,
* 81,102

{"params":[19,20,4,5],"type":"roundHole"},
{"params":[81,20,4,6],"type":"roundHole"},
{"params":[81,102,4,7],"type":"roundHole"},
{"params":[19,102,4,8],"type":"roundHole"},


// @ 25,95 25mm x 10mm - humidity sensor + power
{"params":[25,95,25, 25,10,9],"type":"rectHole"},

Fan
* {"params":[50,55,38,27],"type":"roundHole"}],
